{% set version = '1.0.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-zip
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/zip_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/zip/zip_{{ version }}.tar.gz
  sha256: 6fa9ec7b093b8c717c50f205d4335c31c43c2ecb51c0242c9a0337d8d84df965

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, testthat, withr
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('zip')"           # [not win]
    - "\"%R%\" -e \"library('zip')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/gaborcsardi/zip
  license: CC0
  summary: Cross-Platform 'zip' Compression Library. A replacement for the 'zip' function, that
    does not require any additional external tools on any platform.
  license_family: CC

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: zip
# Title: Cross-Platform 'zip' Compression
# Version: 1.0.0
# Author: Gabor Csardi, Kuba Podgorski, Rich Geldreich
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Description: Cross-Platform 'zip' Compression Library. A replacement for the 'zip' function, that does not require any additional external tools on any platform.
# License: CC0
# LazyData: true
# URL: https://github.com/gaborcsardi/zip
# BugReports: https://github.com/gaborcsardi/zip/issues
# RoxygenNote: 6.0.1
# Suggests: covr, testthat, withr
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2017-04-25 10:54:02 UTC; gaborcsardi
# Repository: CRAN
# Date/Publication: 2017-04-25 14:36:39 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
